[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
arisan_contracts = "BjxGBSpEULzq9kJfx3bGB1rpVHwta8QuP2jeVKow3wN6"

[programs.devnet]
arisan_contracts = "BjxGBSpEULzq9kJfx3bGB1rpVHwta8QuP2jeVKow3wN6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "cargo test -p arisan_contracts --offline --lib --test security_p0 -- --test-threads=1"
