#!/usr/bin/env bash
# Build the CLOCK IN Android APK: the deployed Next app inside a Solana Mobile web shell
# (android/, generated by `solana-mobile webshell init`). Not a TWA: Bubblewrap/TWA breaks
# Mobile Wallet Adapter under Local Network Access (docs/CLOCKIN.md).
#
#   ARISAN_WEB_URL=https://your-deployment.example \
#   SOLANA_MOBILE_KEYSTORE_PASSWORD=... \
#   ./scripts/build-apk.sh
#
# Output: dist/arisan-clockin-<version>.apk (signed release build).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

: "${ARISAN_WEB_URL:?Set ARISAN_WEB_URL to the web app URL the APK opens (https://..., or http://localhost:<port> with adb reverse for testing)}"
: "${SOLANA_MOBILE_KEYSTORE_PASSWORD:?Set SOLANA_MOBILE_KEYSTORE_PASSWORD (6+ chars). Keep it: updates must be signed with the same key.}"

# Wallets and crypto.subtle need a secure context: https, or localhost via adb reverse.
case "$ARISAN_WEB_URL" in
  https://* | http://localhost:* | http://localhost/* | http://127.0.0.1:*) ;;
  *) echo "ARISAN_WEB_URL must be https:// (or http://localhost:<port> for adb reverse testing)" >&2; exit 1 ;;
esac

KEYSTORE="${ARISAN_KEYSTORE_PATH:-$HOME/.config/arisan/arisan-clockin-release.jks}"
ALIAS="${ARISAN_KEYSTORE_ALIAS:-arisan}"
VERSION_NAME="${ARISAN_VERSION_NAME:-$(node -p "require('./package.json').version")}"
VERSION_CODE="${ARISAN_VERSION_CODE:-1}"
SOLANA_MOBILE_CLI="${SOLANA_MOBILE_CLI:-solana-mobile@0.5.0}"

# JDK 17 or 21 for the Android Gradle Plugin
if [[ -z "${JAVA_HOME:-}" ]]; then
  for candidate in \
    "$(/usr/libexec/java_home -v 21 2>/dev/null || true)" \
    "$(/usr/libexec/java_home -v 17 2>/dev/null || true)" \
    /opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home \
    /opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home; do
    if [[ -n "$candidate" && -x "$candidate/bin/java" ]]; then export JAVA_HOME="$candidate"; break; fi
  done
fi
: "${JAVA_HOME:?Install JDK 17 or 21 and set JAVA_HOME}"
export ANDROID_HOME="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Library/Android/sdk}}"

if [[ ! -f "$KEYSTORE" ]]; then
  echo "Creating signing keystore at $KEYSTORE (back it up with its password)"
  mkdir -p "$(dirname "$KEYSTORE")"
  keytool -genkeypair -keystore "$KEYSTORE" -alias "$ALIAS" -keyalg RSA -keysize 2048 \
    -validity 10000 -storepass:env SOLANA_MOBILE_KEYSTORE_PASSWORD \
    -keypass:env SOLANA_MOBILE_KEYSTORE_PASSWORD -dname "CN=Arisan" -noprompt
fi

# Gradle reads ORG_GRADLE_PROJECT_* as project properties, overriding android/gradle.properties.
export ORG_GRADLE_PROJECT_SOLANA_MOBILE_URL="$ARISAN_WEB_URL"
export ORG_GRADLE_PROJECT_SOLANA_MOBILE_VERSION_NAME="$VERSION_NAME"
export ORG_GRADLE_PROJECT_SOLANA_MOBILE_VERSION_CODE="$VERSION_CODE"
export SOLANA_MOBILE_SKIP_VERSION_CHECK=1

npx -y "$SOLANA_MOBILE_CLI" webshell build android \
  --keystore-path "$KEYSTORE" --keystore-alias "$ALIAS" </dev/null

APK_SRC="android/app/build/outputs/apk/release/app-release.apk"
mkdir -p dist
APK="dist/arisan-clockin-$VERSION_NAME.apk"
cp "$APK_SRC" "$APK"

# Verify what was built instead of trusting the build
BUILD_TOOLS="$(ls -d "$ANDROID_HOME"/build-tools/* | sort -V | tail -1)"
"$BUILD_TOOLS/apksigner" verify "$APK" 2>/dev/null
"$BUILD_TOOLS/aapt2" dump badging "$APK" | awk 'NR == 1'
# Count instead of grep -q: an early exit would SIGPIPE unzip and fail under pipefail
if [[ "$(unzip -p "$APK" 'classes*.dex' | LC_ALL=C grep -ac -- "$ARISAN_WEB_URL")" == 0 ]]; then
  echo "Built APK does not contain ARISAN_WEB_URL=$ARISAN_WEB_URL" >&2
  exit 1
fi
echo "URL:    $ARISAN_WEB_URL"
echo "APK:    $APK"
echo "SHA256: $(shasum -a 256 "$APK" | cut -d' ' -f1)"
